### ISSUE TITLE
Phising in my brand nada777

### ISSUE THREAD

**Issue by hades188** [cbuijs/hagezi#3]
The webpage located at https://produkapple.pages.dev/spmb/tariksis.html?upload=NADA777 is engaging in phishing activities under the guise of NADA777. It attempts to deceive users into disclosing personal information through fraudulent means. Immediate action is recommended to investigate and mitigate this fraudulent activity to protect users from potential harm.

**Comment by cbuijs** [comment]
Hi @hades188,

Thanks for reporting. Sorry to hear!

Unfortunally, I do NOT maintain the sources of the lists and/or their content, for questions/problems/etc, please contact the original maintainer here: hagezi@protonmail.com or go to https://github.com/hagezi/dns-blocklists/issues

Good luck!
